"""Add templates table

Revision ID: ad1c3d57153d
Revises: add_agent_health_monitoring
Create Date: 2025-10-23 09:31:03.335992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad1c3d57153d'
down_revision: Union[str, None] = 'add_agent_health_monitoring'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_memory_type', table_name='agent_memory')
    op.create_index(op.f('ix_agent_memory_memory_type'), 'agent_memory', ['memory_type'], unique=False)
    op.drop_column('workflow_executions', 'reasoning_enabled')
    op.drop_column('workflow_executions', 'total_tokens_used')
    op.drop_column('workflow_executions', 'replanning_count')
    op.drop_column('workflow_executions', 'total_reasoning_steps')
    op.drop_column('workflows', 'collaboration_config')
    op.drop_column('workflows', 'allow_replanning')
    op.drop_column('workflows', 'is_dynamic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('is_dynamic', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('allow_replanning', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('collaboration_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflow_executions', sa.Column('total_reasoning_steps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workflow_executions', sa.Column('replanning_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('workflow_executions', sa.Column('total_tokens_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workflow_executions', sa.Column('reasoning_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agent_memory_memory_type'), table_name='agent_memory')
    op.create_index('ix_agent_memory_type', 'agent_memory', ['memory_type'], unique=False)
    # ### end Alembic commands ###
